version: '2'

services:
  nginx:
    image: nginx:1.9.11
    ports:
      - "80:80"      
    network_mode: "bridge" 
    volumes:   
      - /docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /docker/conf/nginx/conf.d:/etc/nginx/conf.d:ro
         
  gitlab:    
    image: gitlab/gitlab-ce:8.5.1-ce.0
    ports:
      - "10080:10080"
    environment:                       
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://gitlab.example.com:10080"
        # Add any other gitlab.rb configuration here, each on its own line 
        # https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template                
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'Richard@mail.ca'
        gitlab_rails['gitlab_email_display_name'] = 'Gitlab'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@mail.ca'
        #timezone
        gitlab_rails['time_zone'] = 'America/New_York'        
        #smtp
        gitlab_rails['smtp_enable'] = true        
        gitlab_rails['smtp_address'] = "smtpserver.mail.ca"
        gitlab_rails['smtp_domain'] = "mail.ca" 	  
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'         
           
    volumes:      
      - /srv/docker/gitlab/gitlab/config:/etc/gitlab
      - /srv/docker/gitlab/gitlab/logs:/var/log/gitlab
      - /srv/docker/gitlab/gitlab/data:/var/opt/gitlab
      - /srv/docker/gitlab/gitlab/logs/reconfigure:/var/log/gitlab/reconfigure
      
    network_mode: "bridge"      